name: Continuous Integration Workflow
on: [push]
jobs:
  call_Continuous_Integration_Workflow:
    uses: Dhwarakesh95/Devops-Stage-1/github-workflows/.github/workflows/reusable-workflows.yml@main
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."