name: CI_Workflow
on: [push]
jobs:
  call_Continuous_Integration_Workflow:
    uses: Devops-Stage-1/github-workflows/.github/workflows/reusable-workflows.yml@main
    with:
      project-key: expense-backend
    secrets:
      vault_token: ${{ secrets.vault_token }}
