name: CI_Workflow
on:
  push:
    branches:
      - main
      - 'EXP-**'
jobs:
  call_Continuous_Integration_Workflow:
    uses: Devops-Stage-1/github-workflows/.github/workflows/ci-reusable-workflows.yml@main
    with:
      project-name: expense-backend
    secrets:
      vault_token: ${{ secrets.vault_token }}
